# This uses an action (crazy-max/ghaction-import-gpg) that assumes you set your
# private key in the `GPG_PRIVATE_KEY` secret and passphrase in the `PASSPHRASE`
# secret. If you would rather own your own GPG handling, please fork this action
# or use an alternative one for key handling.
#
# You will need to pass the `--batch` flag to `gpg` in your signing step
# in `goreleaser` to indicate this is being used in a non-interactive mode.
#
name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'devel'
    tags-ignore:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      current_tag: ${{ env.goreleaser_current_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          # These secrets will need to be configured for the repository:
          gpg_private_key: ${{ secrets.TERRAFORM_GPG_SIGNING_KEY }}
          passphrase: ${{ secrets.TERRAFORM_GPG_SIGN_KEY_PW }}

      - name: Set Tag
        run: |
          echo "goreleaser_current_tag=$(git describe --match 'v*' --tags)" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24

      - name: Set gitea urls
        run: |
          echo "gitea_urls:" >>.goreleaser.yml
          echo "  api: $GITHUB_API_URL" >>.goreleaser.yml
          echo "  download: $GITHUB_SERVER_URL" >>.goreleaser.yml
          echo "  skip_tls_verify: false" >>.goreleaser.yml

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --skip=validate
        env:
          GORELEASER_CURRENT_TAG: "${{ env.goreleaser_current_tag }}"
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GORELEASER_FORCE_TOKEN: 'gitea'
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}

      - name: Save to cache
        uses: actions/cache/save@v4
        with:
          path: dist/*
          key: terraform-provider-routeros-${{ github.run_id }}

  publish:
    runs-on: ubuntu-latest
    needs: release

    container:
      image: ghcr.io/elbandi/tea/tea-runner-image:v0.12.0-22-gba64bca

    steps:
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: dist/*
          key: terraform-provider-routeros-${{ github.run_id }}

      - name: Login to Gitea
        shell: bash
        env:
          GIT_SERVER_URL: ${{ github.server_url }}
          GIT_SERVER_TOKEN: ${{ secrets.TOKEN }}
        run: >-
          tea login ls -o simple |
          grep "$GITHUB_SERVER_URL" >/dev/null ||
          tea login add
          -u "$GIT_SERVER_URL"
          -t "$GIT_SERVER_TOKEN"

      - name: Publish package
        shell: bash
        run: >-
          tea packages terraform publish-provider
          --org terraform
          --provider-name routeros
          --provider-version ${{ needs.release.outputs.current_tag }}
          --path dist
